module Constants
  VOID = "KEYWORD: VOID"
  INT = "KEYWORD: INT"
  FLOAT = "KEYWORD: FLOAT"

  RETURN = 'KEYWORD: RETURN'
  WHILE = 'KEYWORD: WHILE'

  LEFT_PAREN = '('
  RIGHT_PAREN = ')'
  LEFT_BRACKET = '['
  RIGHT_BRACKET = ']'
  SELECTION_STATEMENT = "KEYWORD: IF"
  ELSE = "KEYWORD: ELSE"

end
